spring:
  datasource:
    url: jdbc:mysql://localhost:3306/web
    username: root
    password: 12345
    driver-class-name: com.mysql.jdbc.Driver
    #driver-class-name: org.postgresql.Driver
    initialization-mode: never
  thymeleaf:
    cache: false
    
server:
  port: 8080